require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe NameCardsController do

  # This should return the minimal set of attributes required to create a valid
  # NameCard. As you add validations to NameCard, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # NameCardsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all name_cards as @name_cards" do
      name_card = NameCard.create! valid_attributes
      get :index, {}, valid_session
      assigns(:name_cards).should eq([name_card])
    end
  end

  describe "GET show" do
    it "assigns the requested name_card as @name_card" do
      name_card = NameCard.create! valid_attributes
      get :show, {:id => name_card.to_param}, valid_session
      assigns(:name_card).should eq(name_card)
    end
  end

  describe "GET new" do
    it "assigns a new name_card as @name_card" do
      get :new, {}, valid_session
      assigns(:name_card).should be_a_new(NameCard)
    end
  end

  describe "GET edit" do
    it "assigns the requested name_card as @name_card" do
      name_card = NameCard.create! valid_attributes
      get :edit, {:id => name_card.to_param}, valid_session
      assigns(:name_card).should eq(name_card)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new NameCard" do
        expect {
          post :create, {:name_card => valid_attributes}, valid_session
        }.to change(NameCard, :count).by(1)
      end

      it "assigns a newly created name_card as @name_card" do
        post :create, {:name_card => valid_attributes}, valid_session
        assigns(:name_card).should be_a(NameCard)
        assigns(:name_card).should be_persisted
      end

      it "redirects to the created name_card" do
        post :create, {:name_card => valid_attributes}, valid_session
        response.should redirect_to(NameCard.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved name_card as @name_card" do
        # Trigger the behavior that occurs when invalid params are submitted
        NameCard.any_instance.stub(:save).and_return(false)
        post :create, {:name_card => {  }}, valid_session
        assigns(:name_card).should be_a_new(NameCard)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        NameCard.any_instance.stub(:save).and_return(false)
        post :create, {:name_card => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested name_card" do
        name_card = NameCard.create! valid_attributes
        # Assuming there are no other name_cards in the database, this
        # specifies that the NameCard created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        NameCard.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => name_card.to_param, :name_card => { "these" => "params" }}, valid_session
      end

      it "assigns the requested name_card as @name_card" do
        name_card = NameCard.create! valid_attributes
        put :update, {:id => name_card.to_param, :name_card => valid_attributes}, valid_session
        assigns(:name_card).should eq(name_card)
      end

      it "redirects to the name_card" do
        name_card = NameCard.create! valid_attributes
        put :update, {:id => name_card.to_param, :name_card => valid_attributes}, valid_session
        response.should redirect_to(name_card)
      end
    end

    describe "with invalid params" do
      it "assigns the name_card as @name_card" do
        name_card = NameCard.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        NameCard.any_instance.stub(:save).and_return(false)
        put :update, {:id => name_card.to_param, :name_card => {  }}, valid_session
        assigns(:name_card).should eq(name_card)
      end

      it "re-renders the 'edit' template" do
        name_card = NameCard.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        NameCard.any_instance.stub(:save).and_return(false)
        put :update, {:id => name_card.to_param, :name_card => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested name_card" do
      name_card = NameCard.create! valid_attributes
      expect {
        delete :destroy, {:id => name_card.to_param}, valid_session
      }.to change(NameCard, :count).by(-1)
    end

    it "redirects to the name_cards list" do
      name_card = NameCard.create! valid_attributes
      delete :destroy, {:id => name_card.to_param}, valid_session
      response.should redirect_to(name_cards_url)
    end
  end

end
